title = "Just a Theory"
baseURL = "https://justatheory.com/"
languageCode = "en-us"
theme = "justatheory"

[params]
  favicon = ""
  description = "Theory waxes practical."
  author = "David E. Wheeler"
  bug = "‚ùñ"
  twitter = "theory"
  github = "theory"

[permalinks]
  posts = "/:year/:month/:slug/"
