title = "Just a Theory"
baseURL = "https://justatheory.com/"
languageCode = "en-us"
copyright = "© David E. Wheeler. This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
theme = "justatheory"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsStyle = "monokai"
PreserveTaxonomyNames = true
Paginate = 16
PaginatePath = "p"
footnoteReturnLinkContents = "↩"
enableRobotsTXT = true
disableKinds = ["section"]

[author]
    name = "David E. Wheeler"
    url = "https://justatheory.com/"

[params]
  description = "Irregular fine blogging since 2002."
  author = "David E. Wheeler"
  bug = "❖"
  twitter = "theory"
  github = "theory"
  listTypes = ["post"]
  feedLimit = 32
  icon = "/icon-512x512.png"
  favicon = "/icon-64x64.png"

[permalinks]
  post = "/:year/:month/:slug/"

[mediaTypes]
[mediaTypes."application/atom"]
  suffix = "xml"
[mediaTypes."text/plain"]
  suffix = "text"

[outputFormats]
[outputFormats.atom]
  mediatype = "application/atom"
  baseName = "feed"
[outputFormats.json]
  mediatype = "application/json"
  baseName = "feed"
  isPlainText = true
[outputFormats.text]
  mediatype = "text/plain"
  baseName = "copy"
  suffix = "text"
  isPlainText = true

[outputs]
  home = ["html", "json", "atom"]
  section = ["html", "json", "atom"]
  taxonomy = ["html", "json", "atom"]
  taxonomyTerm = ["html", "json", "atom"]
  page = ["html", "text"]

[taxonomies]
    tag = "tags"